/**
 * /press/: boilerplate, brand palette summary and downloadable assets.
 * The fact sheet itself is assembled on the page from product.ts and
 * launch.ts so it can never disagree with the rest of the site.
 */
import { SITE } from '@/config/site';
import { EDITIONS, FINISHES, PROFILES, formatUsd } from './product';
import { numberWord } from '@/scripts/info/format';

const one = EDITIONS.find((e) => e.id === 'one')!;

export const BOILERPLATE = {
  short: `${SITE.product} is a machined aluminum desktop dial with software-defined haptics. A brushless motor lets firmware decide how the knob feels in each app: clicks, a fluid glide, a spring back to center, hard end stops, or snaps to markers.`,
  long: `${SITE.legalName} makes ${SITE.product}, a desktop dial machined from one billet of 6061 aluminum. Instead of a mechanical click, a brushless gimbal motor and a 14-bit magnetic encoder let firmware decide how the knob feels, and change it in about a millisecond when you switch apps: ${numberWord(PROFILES.length)} feel profiles from crisp frame-by-frame clicks to hard end stops at 0 dB. A round AMOLED display in the knob shows what it controls. ${SITE.product} is local-first, needs no account, and ships with open-source firmware and an open SDK. It costs ${formatUsd(one.priceUsd)}.`,
} as const;

/** Brand palette, as OKLCH tokens (hex is derived at build time). */
export const BRAND_COLORS: { name: string; token: string; oklch: [number, number, number]; role: string }[] = [
  { name: 'Graphite', token: '--graphite-950', oklch: [0.135, 0.006, 355], role: 'Night. The studio at 11 p.m.' },
  { name: 'Aluminum', token: '--alu-100', oklch: [0.935, 0.002, 355], role: 'Ink on night, surfaces on day.' },
  { name: 'White', token: '--white', oklch: [1, 0, 0], role: 'Day. Specs, shop and reading.' },
  { name: 'Tally', token: '--tally', oklch: [0.636, 0.218, 355.3], role: 'The on-air light. One lit thing per view.' },
];

export const LOGOS = [
  { file: '/brand/detent-logo-graphite.svg', label: 'Logo, graphite', use: 'For light backgrounds', dark: false },
  { file: '/brand/detent-logo-white.svg', label: 'Logo, white', use: 'For dark backgrounds', dark: true },
  { file: '/brand/detent-mark-graphite.svg', label: 'Mark, graphite', use: 'Avatars and favicons on light', dark: false },
  { file: '/brand/detent-mark-white.svg', label: 'Mark, white', use: 'Avatars and favicons on dark', dark: true },
] as const;

/** Product renders, one hero per finish (generated by the render pipeline). */
export const RENDERS = FINISHES.map((f) => ({
  finish: f.id,
  name: f.name,
  file: `/renders/${f.id}-hero.webp`,
  foundersOnly: !!f.foundersOnly,
}));

export const COVERAGE_NOTES: string[] = [
  'Detent is a concept product. Everything on this site is real design and engineering work; nothing is for sale, and no units exist to review.',
  'Numbers on this site are design targets for production units. Quote them as targets, not measurements.',
  'The founders and early testers named on this site are fictional. Please do not attribute quotes to them as real people.',
  'Detent is inspired by Scott Bezek’s open-source SmartKnob project. It is not affiliated with it, and he has not endorsed it.',
];
